name: Automated Core Downloader
on:
  workflow_dispatch:

jobs:
  download-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Engine Package
        run: |
          npm install lamejs
          cp node_modules/lamejs/lame.min.js ./lame.min.js

      - name: Push Files Back into Repository Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add lame.min.js
          git commit -m "Add permanent local conversion script" || echo "No changes"
          git push

